Convert List to String before using json_decode
noahfrederick/vim-composer pull request #3
Opened 2016-10-22 17:04 UTC by adriaanzon

Neovim's json_decode() accepts both a String and a List as argument, but
regular vim's json_decode() only accepts a String. Therefore reading
from composer.json with readfile(), and passing the result to
json_decode(), was failing in regular vim.

2016-10-22 17:49 UTC, noahfrederick requested changes
👍 Thanks for this. Looks like we never even call `s:json_decode()` with a string as argument.

2016-10-22 17:49 UTC, noahfrederick commented on autoload/composer.vim
> +      let string = type(a:string) == type([]) ? join(a:string) : a:string
I'm not sure that it matters for our purposes, but strictly speaking this should be `join(a:string, "\n")`.

2016-10-22 17:49 UTC, noahfrederick commented on autoload/composer.vim
>  function! s:json_decode(string) abort
Let's also go ahead and rename the function's `string` parameter to `expr` per Neovim's docs for `json_decode()`.

2016-10-22 22:46 UTC, adriaanzon commented
Cool, I amended your requested changes.

2016-10-23 00:54 UTC, noahfrederick approved these changes

2016-10-23 00:54 UTC, noahfrederick commented
Looks good. Thanks.

2016-10-23 00:55 UTC, merged